name: Publish Policy
on:
  release:
    types: [published]
jobs:
  ftp-upload:
    uses: Majszlinger/Pipelines/.github/workflows/policy-publish.yml@main
    # with:
    #   local-dir: ./policy/
    secrets:
      POLICY_FTP_PASS: ${{ secrets.POLICY_FTP_PASS }}