name: build and push Docker image

on:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string
        outputs:
            tags:
                description: The tag of the built image
                value: ${{ jobs.build.outputs.tags }}


jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        outputs:
            tags: ${{ steps.meta.outputs.tags }}
        steps:
        - name: Check out
          uses: actions/checkout@v2  

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: "tomcsojn/${{ inputs.image-name }}"
            tags: type=sha #,prefix={{branch}}-
            flavor: latest=${{ github.event_name == 'release' }}

        - name: Login to DockerHub
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              GIT_ACCESS_TOKEN=${{ secrets.GIT_ACCESS_TOKEN }}
            secrets: |
              GIT_ACCESS_TOKEN=${{ secrets.GIT_ACCESS_TOKEN }}