name: build and push Docker image

on:
    workflow_call:
        inputs:
            tags:
                required: true
                type: string
            deployment-name:
                required: true
                type: string
            pod-name:
                required: true
                type: string
            namespace:
                required: true
                type: string
        secrets:
            KUBE_CONFIG:
                required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        # if: github.ref == 'refs/heads/master'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
            args: set image deployment/${{ github.event.inputs.deployment-name }} ${{ github.event.inputs.pod-name }}=${{ github.event.inputs.tags }} --insecure-skip-tls-verify -n ${{ github.event.inputs.namespace }}
