name: build and push Docker image

on:
    workflow_call:
        inputs:
            tags:
                required: true
                type: string
            deployment-name:
                required: true
                type: string
            pod-name:
                required: true
                type: string
            namespace:
                required: true
                type: string
        secrets:
            KUBE_CONFIG:
                required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract first image tag
        id: extract-tag
        run: |
          echo "TAG=$(echo '${{ inputs.tags }}' | cut -d',' -f1)" >> $GITHUB_OUTPUT

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/${{ inputs.deployment-name }} ${{ inputs.pod-name }}=${{ steps.extract-tag.outputs.TAG }} --insecure-skip-tls-verify -n ${{ inputs.namespace }}
